# .github/workflows/trigger-gitlab-ci.yml
name: Trigger GitLab CI

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  trigger-gitlab:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Pipeline in GitLab
        env:
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
        run: |
          curl -X POST \
            --fail
            -F "token=$GITLAB_TOKEN" \
            -F "ref=main" \
            https://gitlab.com/api/v4/projects/68947536/trigger/pipeline
